# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: vanbitcase
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: emailapi
service: intern-banao-service

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          path: apidata
          method: any

plugins:
  - serverless-wsgi
  - serverless-offline

custom:
  wsgi:
    app: handler.app
    packRequirements: True
  serverless-offline:
    port: 3000
    host: 0.0.0.0

